create table if not exists public.heliora_players (
  player_id text primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text not null default 'Commandant',
  guild_tag text not null default 'HDH',
  guild jsonb not null default '{}'::jsonb,
  kingdom_power integer not null default 0,
  resources jsonb not null default '{}'::jsonb,
  save_state jsonb not null default '{}'::jsonb,
  save_version integer not null default 2,
  synced_at timestamptz not null default now()
);

alter table public.heliora_players
  add column if not exists user_id uuid unique references auth.users(id) on delete cascade;

alter table public.heliora_players
  add column if not exists save_version integer not null default 2;

create table if not exists public.heliora_chat (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  from_name text not null default 'Alliance',
  message text not null,
  kind text not null default '',
  created_at timestamptz not null default now()
);

alter table public.heliora_chat
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create or replace view public.heliora_leaderboard as
select
  player_id,
  name,
  guild_tag,
  guild,
  kingdom_power,
  synced_at
from public.heliora_players
where user_id is not null;

alter table public.heliora_players enable row level security;
alter table public.heliora_chat enable row level security;

drop policy if exists "heliora players public read" on public.heliora_players;
drop policy if exists "heliora players public insert" on public.heliora_players;
drop policy if exists "heliora players public update" on public.heliora_players;
drop policy if exists "heliora players own read" on public.heliora_players;
drop policy if exists "heliora players own insert" on public.heliora_players;
drop policy if exists "heliora players own update" on public.heliora_players;
drop policy if exists "heliora chat public read" on public.heliora_chat;
drop policy if exists "heliora chat public insert" on public.heliora_chat;
drop policy if exists "heliora chat authenticated read" on public.heliora_chat;
drop policy if exists "heliora chat authenticated insert" on public.heliora_chat;

create policy "heliora players own read"
on public.heliora_players
for select
to authenticated
using (user_id = auth.uid());

create policy "heliora players own insert"
on public.heliora_players
for insert
to authenticated
with check (user_id = auth.uid());

create policy "heliora players own update"
on public.heliora_players
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "heliora chat authenticated read"
on public.heliora_chat
for select
to authenticated
using (true);

create policy "heliora chat authenticated insert"
on public.heliora_chat
for insert
to authenticated
with check (
  user_id = auth.uid()
  and char_length(message) between 1 and 240
);

revoke all on table public.heliora_players from anon;
grant select, insert, update on table public.heliora_players to authenticated;

grant select on public.heliora_leaderboard to anon, authenticated;

revoke all on table public.heliora_chat from anon;
grant select, insert on table public.heliora_chat to authenticated;
grant usage, select on sequence public.heliora_chat_id_seq to authenticated;

insert into public.heliora_chat (from_name, message, kind)
values
  ('Ariane', 'Backend Supabase connecte. Les sauvegardes cloud arrivent.', ''),
  ('Nora', 'Classement et chat sont maintenant partages entre joueurs.', '')
on conflict do nothing;
