create table if not exists public.heliora_players (
  player_id text primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text not null default 'Commandant',
  guild_tag text not null default 'HDH',
  guild jsonb not null default '{}'::jsonb,
  kingdom_power integer not null default 0,
  resources jsonb not null default '{}'::jsonb,
  save_state jsonb not null default '{}'::jsonb,
  save_version integer not null default 2,
  synced_at timestamptz not null default now()
);

alter table public.heliora_players
  add column if not exists user_id uuid unique references auth.users(id) on delete cascade;

alter table public.heliora_players
  add column if not exists save_version integer not null default 2;

create table if not exists public.heliora_chat (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  from_name text not null default 'Alliance',
  message text not null,
  kind text not null default '',
  created_at timestamptz not null default now()
);

alter table public.heliora_chat
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create table if not exists public.heliora_guilds (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  tag text not null unique,
  description text not null default '',
  power integer not null default 0,
  score integer not null default 0,
  member_count integer not null default 1,
  is_open boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.heliora_guild_members (
  guild_id uuid not null references public.heliora_guilds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id text not null,
  name text not null default 'Commandant',
  role text not null default 'member' check (role in ('leader', 'officer', 'member', 'recruit')),
  kingdom_power integer not null default 0,
  contribution integer not null default 0,
  joined_at timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create table if not exists public.heliora_guild_invites (
  id uuid primary key default gen_random_uuid(),
  guild_id uuid not null references public.heliora_guilds(id) on delete cascade,
  invited_email text not null,
  invited_user_id uuid references auth.users(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists heliora_guild_members_user_idx
on public.heliora_guild_members (user_id);

create index if not exists heliora_guild_invites_email_idx
on public.heliora_guild_invites (invited_email, status);

create or replace view public.heliora_leaderboard as
select
  player_id,
  name,
  guild_tag,
  guild,
  kingdom_power,
  synced_at
from public.heliora_players
where user_id is not null;

create or replace view public.heliora_guild_leaderboard as
select
  id,
  name,
  tag,
  score,
  power,
  member_count,
  is_open,
  updated_at
from public.heliora_guilds;

create or replace function public.heliora_is_guild_manager(target_guild uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.heliora_guild_members
    where guild_id = target_guild
      and user_id = auth.uid()
      and role in ('leader', 'officer')
  );
$$;

alter table public.heliora_players enable row level security;
alter table public.heliora_chat enable row level security;
alter table public.heliora_guilds enable row level security;
alter table public.heliora_guild_members enable row level security;
alter table public.heliora_guild_invites enable row level security;

drop policy if exists "heliora players public read" on public.heliora_players;
drop policy if exists "heliora players public insert" on public.heliora_players;
drop policy if exists "heliora players public update" on public.heliora_players;
drop policy if exists "heliora players own read" on public.heliora_players;
drop policy if exists "heliora players own insert" on public.heliora_players;
drop policy if exists "heliora players own update" on public.heliora_players;
drop policy if exists "heliora chat public read" on public.heliora_chat;
drop policy if exists "heliora chat public insert" on public.heliora_chat;
drop policy if exists "heliora chat authenticated read" on public.heliora_chat;
drop policy if exists "heliora chat authenticated insert" on public.heliora_chat;
drop policy if exists "heliora guilds authenticated read" on public.heliora_guilds;
drop policy if exists "heliora guilds owner insert" on public.heliora_guilds;
drop policy if exists "heliora guilds manager update" on public.heliora_guilds;
drop policy if exists "heliora guild members authenticated read" on public.heliora_guild_members;
drop policy if exists "heliora guild members join" on public.heliora_guild_members;
drop policy if exists "heliora guild members self or manager update" on public.heliora_guild_members;
drop policy if exists "heliora guild members self or manager delete" on public.heliora_guild_members;
drop policy if exists "heliora guild invites related read" on public.heliora_guild_invites;
drop policy if exists "heliora guild invites manager insert" on public.heliora_guild_invites;
drop policy if exists "heliora guild invites related update" on public.heliora_guild_invites;

create policy "heliora players own read"
on public.heliora_players
for select
to authenticated
using (user_id = auth.uid());

create policy "heliora players own insert"
on public.heliora_players
for insert
to authenticated
with check (user_id = auth.uid());

create policy "heliora players own update"
on public.heliora_players
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "heliora chat authenticated read"
on public.heliora_chat
for select
to authenticated
using (true);

create policy "heliora chat authenticated insert"
on public.heliora_chat
for insert
to authenticated
with check (
  user_id = auth.uid()
  and char_length(message) between 1 and 240
);

create policy "heliora guilds authenticated read"
on public.heliora_guilds
for select
to authenticated
using (true);

create policy "heliora guilds owner insert"
on public.heliora_guilds
for insert
to authenticated
with check (owner_user_id = auth.uid());

create policy "heliora guilds manager update"
on public.heliora_guilds
for update
to authenticated
using (public.heliora_is_guild_manager(id) or owner_user_id = auth.uid())
with check (public.heliora_is_guild_manager(id) or owner_user_id = auth.uid());

create policy "heliora guild members authenticated read"
on public.heliora_guild_members
for select
to authenticated
using (true);

create policy "heliora guild members join"
on public.heliora_guild_members
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    exists (
      select 1
      from public.heliora_guilds
      where id = guild_id
        and (is_open = true or owner_user_id = auth.uid())
    )
  )
);

create policy "heliora guild members self or manager update"
on public.heliora_guild_members
for update
to authenticated
using (user_id = auth.uid() or public.heliora_is_guild_manager(guild_id))
with check (user_id = auth.uid() or public.heliora_is_guild_manager(guild_id));

create policy "heliora guild members self or manager delete"
on public.heliora_guild_members
for delete
to authenticated
using (user_id = auth.uid() or public.heliora_is_guild_manager(guild_id));

create policy "heliora guild invites related read"
on public.heliora_guild_invites
for select
to authenticated
using (
  public.heliora_is_guild_manager(guild_id)
  or invited_user_id = auth.uid()
  or lower(invited_email) = lower(auth.jwt() ->> 'email')
);

create policy "heliora guild invites manager insert"
on public.heliora_guild_invites
for insert
to authenticated
with check (
  created_by = auth.uid()
  and public.heliora_is_guild_manager(guild_id)
);

create policy "heliora guild invites related update"
on public.heliora_guild_invites
for update
to authenticated
using (
  public.heliora_is_guild_manager(guild_id)
  or invited_user_id = auth.uid()
  or lower(invited_email) = lower(auth.jwt() ->> 'email')
)
with check (
  public.heliora_is_guild_manager(guild_id)
  or invited_user_id = auth.uid()
  or lower(invited_email) = lower(auth.jwt() ->> 'email')
);

revoke all on table public.heliora_players from anon;
grant select, insert, update on table public.heliora_players to authenticated;

grant select on public.heliora_leaderboard to anon, authenticated;
grant select on public.heliora_guild_leaderboard to anon, authenticated;

revoke all on table public.heliora_chat from anon;
grant select, insert on table public.heliora_chat to authenticated;
grant usage, select on sequence public.heliora_chat_id_seq to authenticated;

revoke all on table public.heliora_guilds from anon;
revoke all on table public.heliora_guild_members from anon;
revoke all on table public.heliora_guild_invites from anon;
grant select, insert, update on table public.heliora_guilds to authenticated;
grant select, insert, update, delete on table public.heliora_guild_members to authenticated;
grant select, insert, update on table public.heliora_guild_invites to authenticated;

insert into public.heliora_chat (from_name, message, kind)
values
  ('Ariane', 'Backend Supabase connecte. Les sauvegardes cloud arrivent.', ''),
  ('Nora', 'Classement et chat sont maintenant partages entre joueurs.', '')
on conflict do nothing;
