create table if not exists public.heliora_players (
  player_id text primary key,
  name text not null default 'Commandant',
  guild_tag text not null default 'HDH',
  guild jsonb not null default '{}'::jsonb,
  kingdom_power integer not null default 0,
  resources jsonb not null default '{}'::jsonb,
  save_state jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create table if not exists public.heliora_chat (
  id bigint generated by default as identity primary key,
  from_name text not null default 'Alliance',
  message text not null,
  kind text not null default '',
  created_at timestamptz not null default now()
);

alter table public.heliora_players enable row level security;
alter table public.heliora_chat enable row level security;

drop policy if exists "heliora players public read" on public.heliora_players;
drop policy if exists "heliora players public insert" on public.heliora_players;
drop policy if exists "heliora players public update" on public.heliora_players;
drop policy if exists "heliora chat public read" on public.heliora_chat;
drop policy if exists "heliora chat public insert" on public.heliora_chat;

create policy "heliora players public read"
on public.heliora_players
for select
to anon
using (true);

create policy "heliora players public insert"
on public.heliora_players
for insert
to anon
with check (true);

create policy "heliora players public update"
on public.heliora_players
for update
to anon
using (true)
with check (true);

create policy "heliora chat public read"
on public.heliora_chat
for select
to anon
using (true);

create policy "heliora chat public insert"
on public.heliora_chat
for insert
to anon
with check (char_length(message) between 1 and 240);

insert into public.heliora_chat (from_name, message, kind)
values
  ('Ariane', 'Backend Supabase connecte. Les sauvegardes cloud arrivent.', ''),
  ('Nora', 'Classement et chat sont maintenant partages entre joueurs.', '')
on conflict do nothing;
